name: schedule
on:
  schedule:
    - cron: "0 3 1 * *"

jobs:
  delete:
    name: Delete bot messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nodenv/actions/node-version@main
        id: nodenv
      - name: Use Node.js ${{ steps.nodenv.outputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nodenv.outputs.node-version }}"
      - name: mask channels
        run: |
          set -eu
          arr=($(echo "$CHANNELS" | tr ',' "$IFS"))
          for c in "${arr[@]}"; do echo "::add-mask::${c}"; done
        env:
          CHANNELS: ${{ secrets.SLACK_CHANNELS }}
      - name: yarn install, and yarn start
        run: |
          yarn install
          yarn start
        env:
          CI: true
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CHANNELS: ${{ secrets.SLACK_CHANNELS }}
